server:
  port: 7140

spring:
  application:
    name: sleuth
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port} 