server:
  port: 7110
  
spring:
  application:
    name: zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port} 
        
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-hi
    api-b:
      path: /api-b/**
      serviceId: client      