server:
  port: 7110
  
spring:
  application:
    name: zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port} 
        
zuul:
  add-host-header: true
  sensitive-headers:  
  routes:
    sso:
      path: /**
      serviceId: sso 
      
      
