spring:
  application:
    name: sso
  datasource:
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  redis:
    database: 5
    host: localhost
    port: 6379
    password: 
    pool:
      max-active: 300
      max-wait: 100000
      max-idle: 100
      min-idle: 0
    timeout: 300
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    
server:
  port: 8001
#  context-path: /sso

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}  
    


logging:
  level:
    org.springframework.security: INFO