server:
  port: 6100
  

spring:
  zipkin:
    base-url: http://localhost:7140
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7100/eureka/
  instance:
    prefer-ip-address:  true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}  